# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Expand-CollapseHeaderWithTabs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Expand-CollapseHeaderWithTabs

  pod MaterialComponents/Tabs+TabBarView


  target 'Expand-CollapseHeaderWithTabsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
